apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
  namespace: ebank
  labels:
    app: discoveryserver
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: http
  selector:
    app: discoveryserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver
  namespace: ebank
  labels:
    app: discoveryserver
spec:
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: h4mdi/ebank-discoveryserver:latest
          ports:
            - containerPort: 8761
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
